apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"