apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::127451597072:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-l80wWADpK47p
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system: roboshop-trainee
      userarn: arn:aws:iam::127451597072:user/sravani
      username: sravani
    - groups:
      - system: roboshop-admin
      userarn: arn:aws:iam::127451597072:user/sandhya
      username: sravani
kind: ConfigMap
metadata:
  creationTimestamp: "2026-10-02T02:34:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1260"
  uid: f261cf6c-7ec4-4cd6-a253-a73d0a07264f
