apiVersion: v1
kind: pod
metadata:
  name: emptydir-pod
spec:
  containers:
   - name: emptydir-container
    image: nginx
    volumeMounts:
     - mountPath: /var/log/nginx
      name: nginx-log 
   - name: almalinux
    image: almalinux:9
    volumeMounts:
     - mountPath: /mnt/nginx
      name: nginx-log
  volumes:
   - name: nginx-log
    emptyDir:
      sizeLimit: 500Mi
